### PR TITLE
Add metrics to storage

### PR DESCRIPTION
**Pull request by fmueller**
This PR adds:
- metrics endpoint to storage
- technical default metrics for zmon
- automatic metrics curation on an intervall
- metrics for number of APIs in different status and lifecycle states (which can be later used for data-based decision making)

### CODE REVIEW

**Comment by fmueller** [comment]
Still have to make interval of metrics collection configurable. Will do this tomorrow.

**Comment by fmueller** [comment]
@maxim-tschumak Can your please review this although Travis CI currently has stability issues?

**Comment by maxim-tschumak** [comment]
Great! I've already tested the functionality, it works.

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
