### PR TITLE
Enabled running swagger-ui without OAuth integration

### PR DESCRIPTION
**Pull request by maxim-tschumak**
#24 Improving frontend development workflow: 
* Adding readme file including how-to start swagger-ui locally with and without oauth2.

### CODE REVIEW

**Comment by fmueller** [comment]
Can you also add explanation on how to run swagger-ui locally without docker (and without OAuth2)? Ramping up docker container all the time, it quite time consuming in frontend development workflow.

**Comment by maxim-tschumak** [comment]
Good point @fmueller, for development purposes it would be too much overhead to build/start docker every time. Next changes include:
- Build and bundle the resources using Gulp (incl. node server)
- Simplifying Dockerfile (same structure for testing and docker env.)
- Starting the node server as well when `gulp serve`
- Default config doesn't use OAuth
- OAuth integration with `gulp serve-with-oauth`
- Readme about how to start the app locally with/without OAuth integration

**Comment by maxim-tschumak** [comment]
FYI: There is no proper toggle for enabling/disabling OAuth integration in the frontend. Currently, if redirect URL is not set, the user is not being redirected to OAuth server (https://github.com/zalando-incubator/api-discovery/blob/master/swagger-ui/src/main/javascript/SwaggerUi.js#L38).
I think we should implement it in the separate ticket. What do you think, @fmueller?

**Comment by fmueller** [comment]
👍 

Good idea with the oauth toggle. Otherwise it's not possible in frontend to distinguish between wrongly configured OAuth integration and just disabled one.

**Comment by maxim-tschumak** [comment]
ok, thanks for creating an issue :)

**Pull request merged**
