### PR TITLE
Test data for storage service and run-all script

### PR DESCRIPTION
**Pull request by maxim-tschumak**
This PR covers #31 and #8.

- Test data for storage service
- Script to load test data to storage service
- Run-all script that builds the respective projects, starts docker-compose and loads test data
- Docu adjustments and improvements

@fmueller would be nice if you find some time to test the script on mac.

### CODE REVIEW

**Comment by fmueller** [comment]
Tried it out locally.

First I had to install `coreutils` because `realpath` command was not found. `brew install coreutils`fixed this. Then the script runs.

But it failed at the end with: `curl: (7) Failed to connect to 192.168.99.100 port 8010: Connection refused`

192.168.99.100 is my docker-machine ip

**Comment by maxim-tschumak** [comment]
Thank you for checking this!
Our setup defaults to `localhost` as docker host and we forward/open all the ports (swagger-ui, storage and postgres). It looks like the ports might be accessible over localhost (https://docs.docker.com/docker-for-mac/) and the docker host workaround is not needed anymore.

What happens when you just run `./start.sh`?

**Comment by fmueller** [comment]
The script is working. It turns out the sleep interval after docker-compose is not enough on my machine. If I increase the interval it is working.

What about waiting for correct log output like in https://github.com/zalando-incubator/zally/blob/master/.travis.yml#L34 or curl on storage/apps and wait till it returns something?

**Comment by maxim-tschumak** [comment]
Cool, thanks for the hint! Will do so!
Have you tried `./start.sh`?  (If it works with localhost on Mac, we can simplify the start script)

**Comment by fmueller** [comment]
Because you still have to run docker vm with its own ip, it does not work.

**Comment by maxim-tschumak** [comment]
OK, thanks! I'll do the mentioned improvements.

**Comment by maxim-tschumak** [comment]
Update:
- Periodically checking storage service is implemented
- `realpath` is not needed anymore

**Comment by fmueller** [comment]
👍

**Pull request merged**
