### PR TITLE
Add bookmarkable links

### LINKED ISSUE #6: Add bookmarkable URLs for API definition detail page
In order to improve collaboration, a loaded API definition details page should be bookmarkable.

### PR DESCRIPTION
**Pull request by fmueller**
Fixes #6

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
Sometimes (90%) when loading the front page, I get this JS exception:
`Uncaught TypeError: Cannot read property 'length' of undefined (index.js:24)`
There are also some other exceptions when there are no active applications/apis in the storage available (less important).

Can you please check this @fmueller?

**Comment by fmueller** [comment]
This is related to test data and that's why I didn't investigate it so far.

But I probably should...

**Comment by fmueller** [comment]
@maxim-tschumak The first error message you mention was introduced earlier. I also receive it on current master branch.

**Comment by maxim-tschumak** [comment]
@fmueller I've created an issue (#50) for the bug in the master.

**Comment by fmueller** [comment]
@maxim-tschumak Thanks :) Can we merge this now?

**Comment by maxim-tschumak** [comment]
:+1:

**Pull request merged**
